---
# ====== Application: Oracle Integration Observability =======
id: 101
identification: 
  name: Oracle Integration Observability
  alias: ORACLE-INTEGRATION-OBSERVABILITY
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 15878029480683267

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: OIO_APEX

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Browser (use browser language preference)
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Oracle Integration Observability

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Monitoring Dashboard

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 15878862362683273

navigation-bar: 
  implementation: List
  list: Navigation Bar # 15879978021683304
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_FILES#css/oio.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 47039818849726

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Oracle Integration Observability

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 15873563730683252
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 47039289583388

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 15873805553683255
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 15874161362683256
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 15874474134683257
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 15874786829683257
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 15875084550683258
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 15875335801683259
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 15875612046683259
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 15875997476683260
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 15876229553683261
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 47039289583392

- # ====== Component Setting: NATIVE_IR ========================
  id: 15876534454683261
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 47039289583394

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 15876852265683262
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 47039289583394

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 15877120383683263
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 47039289583394

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 15877454680683263
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 47039289583394

language-mappings: 
- # ====== Language Mapping: Portuguese (Brazil) (pt-br) =======
  id: 17684489431369236
  attributes: 
    translation-application: 10002
    language: Portuguese (Brazil) (pt-br)

  globalization: 
    document-direction: Left-To-Right

