prompt ============================================================
prompt oio_trace 2.0 - master table, identity, partitioning, indexes and comments
prompt ============================================================
prompt Execute as the application schema owner, for example OIO_OWNER.
prompt oio_trace is the transaction/master record in the 2.0 model.
prompt ============================================================

set define off

create table oio_trace (
    trace_id            number generated by default on null as identity,
    integration_key     varchar2(250 byte) not null,
    log_ref_id          varchar2(250 byte),
    oic_instance_id     varchar2(250 byte) not null,
    user_name           varchar2(250 byte) not null,
    log_level           char(1 byte) not null,
    summary             varchar2(4000 byte) not null,
    error_code          varchar2(250 byte),
    error_message       varchar2(4000 byte),
    attr1_value         varchar2(4000 byte) not null,
    attr2_value         varchar2(4000 byte),
    attr3_value         varchar2(4000 byte),
    attr4_value         varchar2(4000 byte),
    attr5_value         varchar2(4000 byte),
    attr6_value         varchar2(4000 byte),
    attr7_value         varchar2(4000 byte),
    attr8_value         varchar2(4000 byte),
    attr9_value         varchar2(4000 byte),
    attr10_value        varchar2(4000 byte),
    transaction_id1     varchar2(250 byte),
    transaction_id2     varchar2(250 byte),
    transaction_id3     varchar2(250 byte),
    creation_date       timestamp(6) default systimestamp,
    last_update_date    timestamp(6),
    constraint oio_trace_pk primary key (trace_id),
    constraint oio_trace_integration_fk foreign key (integration_key)
        references oio_integration_cfg (integration_key),
    constraint oio_trace_level_ck check (log_level in ('I','E'))
)
partition by range (creation_date)
interval (numtoyminterval(1, 'MONTH'))
(
    partition p_initial values less than (timestamp '2026-01-01 00:00:00')
);

prompt TRACE_ID uses an Oracle identity column.
prompt Oracle creates and manages the underlying ISEQ$ identity sequence automatically.
prompt No standalone sequence or trigger is required for oio_trace.

create index oio_trace_integration_ix on oio_trace (integration_key, creation_date) local;
create index oio_trace_level_ix on oio_trace (log_level, creation_date) local;
create index oio_trace_ref_ix on oio_trace (log_ref_id, creation_date) local;
create index oio_trace_instance_ix on oio_trace (oic_instance_id, creation_date) local;
create index oio_trace_attr1_ix on oio_trace (attr1_value, creation_date) local;
create index oio_trace_error_code_ix on oio_trace (error_code) global;

create index oio_trace_txn_id1_ix on oio_trace (transaction_id1) global;
create index oio_trace_txn_id2_ix on oio_trace (transaction_id2) global;
create index oio_trace_txn_id3_ix on oio_trace (transaction_id3) global;
create index oio_trace_txn_lookup_ix on oio_trace (
    integration_key,
    transaction_id1,
    transaction_id2,
    transaction_id3
) global;

comment on table oio_trace is
    'Traceability master table. Stores the current transaction-level state and stable execution/business identifiers. Status history is stored in oio_trace_event.';
comment on column oio_trace.trace_id is
    'Unique trace log master identifier generated by an Oracle identity column.';
comment on column oio_trace.integration_key is
    'Foreign key to oio_integration_cfg. Identifies the configured integration.';
comment on column oio_trace.log_ref_id is
    'Correlation or transaction reference ID.';
comment on column oio_trace.oic_instance_id is
    'Oracle Integration execution instance identifier associated with the master event.';
comment on column oio_trace.user_name is
    'User, service account, or component that registered the master trace event.';
comment on column oio_trace.log_level is
    'Current master severity. I = informational or success state, E = error or fault state.';
comment on column oio_trace.summary is
    'Current short functional or technical summary for the transaction.';
comment on column oio_trace.error_code is
    'Current technical or business error code when applicable.';
comment on column oio_trace.error_message is
    'Current technical or business error message when applicable.';
comment on column oio_trace.attr1_value is
    'Mandatory metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR1_NAME.';
comment on column oio_trace.attr2_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR2_NAME.';
comment on column oio_trace.attr3_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR3_NAME.';
comment on column oio_trace.attr4_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR4_NAME.';
comment on column oio_trace.attr5_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR5_NAME.';
comment on column oio_trace.attr6_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR6_NAME.';
comment on column oio_trace.attr7_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR7_NAME.';
comment on column oio_trace.attr8_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR8_NAME.';
comment on column oio_trace.attr9_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR9_NAME.';
comment on column oio_trace.attr10_value is
    'Optional metadata-driven business KPI or identifier value. Meaning is defined by oio_integration_cfg.ATTR10_NAME.';
comment on column oio_trace.transaction_id1 is
    'Optional business-defined transaction identifier used by OIC to correlate, locate, update, or upsert business transaction status.';
comment on column oio_trace.transaction_id2 is
    'Optional business-defined secondary transaction identifier used by OIC to correlate, locate, update, or upsert business transaction status.';
comment on column oio_trace.transaction_id3 is
    'Optional business-defined tertiary transaction identifier used by OIC to correlate, locate, update, or upsert business transaction status.';
comment on column oio_trace.creation_date is
    'Master trace creation timestamp and partitioning key.';
comment on column oio_trace.last_update_date is
    'Master trace last update timestamp. Updated when the current transaction state changes.';




