prompt ============================================================
prompt oio_trace_event 2.0 - detail/history table, identity, partitioning, indexes and comments
prompt ============================================================
prompt Execute as the application schema owner, for example OIO_OWNER.
prompt oio_trace_event stores the event and transaction status history.
prompt ============================================================

set define off

create table oio_trace_event (
    trace_detail_id     number generated by default on null as identity,
    trace_id            number not null,
    event_type          varchar2(50 byte),
    step_name           varchar2(250 byte),
    oic_instance_id     varchar2(250 byte),
    user_name           varchar2(250 byte),
    log_level           char(1 byte),
    summary             varchar2(4000 byte),
    error_code          varchar2(250 byte),
    error_message       varchar2(4000 byte),
    transaction_status  varchar2(250 byte),
    creation_date       timestamp(6) default systimestamp not null,
    last_update_date    timestamp(6),
    constraint oio_trace_event_pk primary key (trace_detail_id),
    constraint oio_event_trace_fk foreign key (trace_id)
        references oio_trace (trace_id) on delete cascade,
    constraint oio_event_level_ck check (log_level is null or log_level in ('I','E'))
)
partition by range (creation_date)
interval (numtoyminterval(1, 'MONTH'))
(
    partition p_initial values less than (timestamp '2026-01-01 00:00:00')
);

prompt TRACE_DETAIL_ID uses an Oracle identity column.
prompt Oracle creates and manages the underlying ISEQ$ identity sequence automatically.
prompt No standalone sequence or trigger is required for oio_trace_event.

create index oio_event_trace_ix on oio_trace_event (trace_id, creation_date) local;
create index oio_event_status_ix on oio_trace_event (transaction_status, creation_date) local;
create index oio_event_level_ix on oio_trace_event (log_level, creation_date) local;
create index oio_event_type_ix on oio_trace_event (event_type, creation_date) local;
create index oio_event_error_code_ix on oio_trace_event (error_code, creation_date) local;
create index oio_event_trace_g_ix
    on oio_trace_event (trace_id) global;
	
comment on table oio_trace_event is
    'Traceability detail table. Stores the chronological history of events and business transaction status changes for each oio_trace master record.';
comment on column oio_trace_event.trace_detail_id is
    'Unique trace log detail identifier generated by an Oracle identity column.';
comment on column oio_trace_event.trace_id is
    'Reference to oio_trace.TRACE_ID master record.';
comment on column oio_trace_event.event_type is
    'Optional technical classification of the detail event, such as creation, status update, success event, or error event.';
comment on column oio_trace_event.step_name is
    'Optional integration step or logical business step related to the event.';
comment on column oio_trace_event.oic_instance_id is
    'Oracle Integration execution instance identifier related to this detail event when available.';
comment on column oio_trace_event.user_name is
    'User, service account, or component that registered this detail event.';
comment on column oio_trace_event.log_level is
    'Detail event severity. I = informational or success event, E = error or fault event. Nullable for pure status history entries.';
comment on column oio_trace_event.summary is
    'Short functional or technical summary for this detail event.';
comment on column oio_trace_event.error_code is
    'Technical or business error code for this detail event when applicable.';
comment on column oio_trace_event.error_message is
    'Technical or business error message for this detail event when applicable.';
comment on column oio_trace_event.transaction_status is
    'Business-defined transaction lifecycle/status captured at this point in the history. Valid values are defined by each business process.';
comment on column oio_trace_event.creation_date is
    'Detail event creation timestamp and partitioning key.';
comment on column oio_trace_event.last_update_date is
    'Detail event last update timestamp.';



