prompt ============================================================
prompt oio_trace_payload 2.0 - payload LOB table, identity, partitioning, indexes and comments
prompt ============================================================
prompt Execute as the application schema owner, for example OIO_OWNER.
prompt oio_trace_payload replaces oio_trace_eventS as the payload storage table.
prompt ============================================================

set define off

create table oio_trace_payload (
    trace_lob_id    number generated by default on null as identity,
    trace_detail_id number not null,
    request         clob,
    response        clob,
    creation_date   timestamp(6) default systimestamp not null,
    constraint oio_trace_payload_pk primary key (trace_lob_id),
    constraint oio_payload_event_fk foreign key (trace_detail_id)
        references oio_trace_event (trace_detail_id) on delete cascade
)
partition by range (creation_date)
interval (numtoyminterval(1, 'MONTH'))
(
    partition p_initial values less than (timestamp '2026-01-01 00:00:00')
);

prompt TRACE_LOB_ID uses an Oracle identity column.
prompt Oracle creates and manages the underlying ISEQ$ identity sequence automatically.
prompt No standalone sequence or trigger is required for oio_trace_payload.

create index oio_payload_event_ix on oio_trace_payload (trace_detail_id, creation_date) local;
create index oio_payload_event_g_ix
    on oio_trace_payload (trace_detail_id) global;

comment on table oio_trace_payload is
    'Large request and response payload storage for traceability detail events. This table replaces oio_trace_eventS in the 2.0 model and keeps CLOB fields separated from oio_trace and oio_trace_event for performance.';
comment on column oio_trace_payload.trace_lob_id is
    'Unique trace payload LOB identifier generated by an Oracle identity column.';
comment on column oio_trace_payload.trace_detail_id is
    'Reference to oio_trace_event.TRACE_DETAIL_ID event record that owns the payload.';
comment on column oio_trace_payload.request is
    'Full or sanitized request payload stored as CLOB when required by the integration support model.';
comment on column oio_trace_payload.response is
    'Full or sanitized response or error payload stored as CLOB when required by the integration support model.';
comment on column oio_trace_payload.creation_date is
    'Payload record creation timestamp and partitioning key.';



